import generateErrorUtil from "../../utils/generateErrorUtil.js";
import axios from 'axios';

const todaysGamesController = async (req, res, next) => {
    try {
        const res = await 
    } catch (err) {
        next(err)
    }
}

export default todaysGamesController;